/* This file gathers descriptions of globals types and variables */
#include <stdio.h>

#ifndef TRUE
#define TRUE (1)
#define FALSE (0)
#endif

typedef long int32;			/* a cell */
typedef unsigned long uint32;		/* an unsigned cell */

extern int32 cycle;			/* cycle number */
extern int phase;			/* phase number */

extern int genvectors;			/* if TRUE, generate test vectors */
extern int tracing;			/* if TRUE, generate instruction
					   and data address trace */
extern int summarize;			/* if TRUE, summarize cycle types,etc */

extern int quitflag;			/* set by terminate in fakeio */

/* public functions */
/* this list was generated by typing:
fgdeclare main.c aluops.c fakeio.c vectors.c save.c fsim4c.c trace.c fkscrn4b.c
*/
int32 Addop();
void Quit();
int32 Fakeio();
void Fakeioarg();
FILE * Vecopen();
void Vecclose();
void Vecldphia();
void Vecldphib();
void Vecstphia();
void Vecstphib();
void Vecintphia();
void Vecintphib();
void Vecdmaphia();
void Vecdmaphib();
void Vecinton();
void Vecintoff();
FILE * Saveopen();
void Saveclose();
void Resetobj();
void Savecore();
void Startup();
void Saveobj();
int32 Fetchexternal();
int32 Fetchexternalbyte();
void Storeexternal();
void Storeexternalbyte();
void Cycle();
void Phase();
void Singlestep();
void Settrap();
void Sim();
void Simcycles();
void Resetregs();
void Startat();
void Stack();
void Waitcycle();
void Dmastart();
void Dmaend();
void Interrupton();
void Interruptoff();
void Clearstats();
void Summary();
void Tracemode();
void Vectormode();
void Visualmode();
FILE * Traceopen();
void Trace();
void Logliteral();
void Traceclose();
int Getcmdc();
void Dump();
void Cmdcharput();
int Cmdcharget();
void Cmdmsg();
void Iowrite();
void Ioread();
void Visopen();
void Visclose();
void Updatescr();
